### ISSUE TITLE
Are you actually able to set a customer color by passing in a hex value?

### ISSUE THREAD

**Issue by pgregg88** [mikemucc/screenlogic-api#4]
I'm thrilled to find this and can hardly wait to dig in. It's been almost a year since I took a crack at learning node.js to get an early version of parnic working.

Are you able to set a custom color now or are the hex values just for rendering the preset color button on a UI? Thanks.

**Comment by mikemucc** [comment]
At this point, the Hex values are only for rendering the buttons on the UI.

I'm pretty sure that being able to send custom colors to Intellibrite lights is a goal that parnic has for the underlying library, and as soon as that exists, I'll implement endpoints for it, because I really want that as well.
